# Generated by Django 2.2.1 on 2019-05-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lname',
        ),
    ]
